name: Auto Author Assign

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    name: Auto assign author
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§‘ğŸ»â€ğŸ’» Automatically assign an author
        uses: toshimaru/auto-author-assign@v2.1.1
